config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :posts
  resources :glucoses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/glucose.rb
class Glucose < ApplicationRecord
  validates :date, presence: true
  validates :before_breakfast_glucose, :after_breakfast_glucose, :before_lunch_glucose, :after_lunch_glucose,
  :before_dinner_glucose, :after_dinner_glucose, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  has_one_attached :image
  belongs_to :user
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers:[:google_oauth2]

  has_many :sns_credentials
  validates :name, presence: true

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :profile])
  end
end

app/controllers/glucoses_controller.rb
class GlucosesController < ApplicationController

  def index
    @glucoses = Glucose.all
  end

  def new
    @glucose = Glucose.new
  end

  def create
    @glucose = Glucose.new(glucose_params)
    if @glucose.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @glucose = Glucose.find(params[:id])
  end

  private
  def glucose_params
    params.require(:glucose).permit(:date, :before_breakfast_glucose, :after_breakfast_glucose, :before_lunch_glucose, :after_lunch_glucose, :before_dinner_glucose, :after_dinner_glucose, :remarks_section)
  end


  def move_to_index
    unless user_signed_in?
     redirect_to action: :index
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post= Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end


  def edit
  end

private
  def post_params
    params.require(:post).permit(:content).merge(user_id:current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
   end

   private
   def authorization
    begin
      sns_info = User.from_omniauth(request.env["omniauth.auth"])
      @user = sns_info[:user]

      if @user.persisted? && @user.active_for_authentication?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      else
        @sns_id = sns_info[:sns].id
        render template: 'devise/registrations/new'
      end
    rescue StandardError => e
      flash[:alert] = "There was a problem signing you in: #{e.message}"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    Rails.logger.debug("Params: #{params.inspect}")
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      if params[:user]
        params[:user][:password] = pass
        params[:user][:password_confirmation] = pass
      else
        Rails.logger.error("params[:user] is nil")
      end
    end
    super
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :profile])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glucoses_helper.rb
module GlucosesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/glucoses/index.html.erb
<div class= "glucose_nav">
 <p>血糖値管理表<i class="fa-solid fa-syringe"></i></p>
</div>
<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>朝食前</th>
      <th>朝食後</th>
      <th>昼食前</th>
      <th>昼食後</th>
      <th>夕食前</th>
      <th>夕食後</th>
      <th>備考欄</th>
    </tr>
  </thead>
  <tbody>
    <% @glucoses.each do |g| %>
      <tr>
        <td><%= g.date %></td>
        <td><%= g.before_breakfast_glucose %></td> 
        <td><%= g.after_breakfast_glucose %></td> 
        <td><%= g.before_lunch_glucose %></td> 
        <td><%= g.after_lunch_glucose %></td> 
        <td><%= g.before_dinner_glucose %></td> 
        <td><%= g.after_dinner_glucose %></td> 
        <td><%= g.remarks_section %></td> 
      </tr>
     <% end %>
  </tbody>
</table>

app/views/glucoses/new.html.erb
<%= form_with model: @glucose, local: true do |g| %>
<div class= "glucose_nav">
 <p>血糖値管理表<i class="fa-solid fa-syringe"></i></p>
</div>
  <table>
     <thead>
       <tr>
         <th>日付</th>
          <th>朝食前</th>
          <th>朝食後</th>
          <th>昼食前</th>
          <th>昼食後</th>
          <th>夕食前</th>
          <th>夕食後</th>
          <th>備考欄</th>
        </tr>
      </thead>
        <tbody>
          <tr>
            <td><%= g.date_field :date, class:"glucose-data" %></td>
            <td><%= g.text_field :before_breakfast_glucose %></td>
            <td><%= g.text_field :after_breakfast_glucose %></td>
            <td><%= g.text_field :before_lunch_glucose %></td>
            <td><%= g.text_field :after_lunch_glucose %></td>
            <td><%= g.text_field :before_dinner_glucose %></td>
            <td><%= g.text_field :after_dinner_glucose %></td>
            <td><%= g.text_area :remarks_section ,class:"glucose_remarks" %></td>
           </tr>
        </tbody>
   </table> 
   <div class="btn-actions">
    <%= g.submit '保存' %>
  </div>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My-Glucose</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body> 
</html>

app/views/posts/index.html.erb
<% @posts.each do |form| %>
 <div class="timeline-post">
    <div class="content_post">
      <p><%= form.content %></p>
      <p><% form.image %></p>
       <div class="users_nav_info">
         <%= link_to form.user.name, post_path(form.id) %>
       </div>
    </div>  
 </div>
<% end %>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
   <div class="title">みんなに情報を共有しよう</div>
    <%= form_with(model: @post, local: true) do |post| %>
      <%= post.text_area :content, placeholder: "text", rows: "10" %>
      <%= post.file_field :"image", id:"image" %>
      <%= post.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="timeline-post">
    <div class="content_post">
      <p><%= @post.content %></p>
      <p><% @post.image %></p>
       <div class="users_nav_info">
        <%= @post.user.name %>
       </div>
    </div>  
 </div>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header__bar row">
    <h1 class="grid-6"><a href="/">My-Glucose<i class="fa-solid fa-syringe"></i></a></h1>
      <div class="user_nav grid-6">
        <%= link_to "投稿", new_post_path, class: "post" %>
      </div>
      <div class="users_info">
        <% if user_signed_in? %>
          <%= current_user.name %> さん
        <% else %>
           ゲストユーザーさん
        <% end %>
      </div>
      <%= render "shared/sidebar" %>
   </div>
</header>

app/views/shared/_sidebar.html.erb
<div class="header-content">
    <div class="hamburger-menu" id="hamburger-menu">
       <i class="fas fa-bars"></i> 
    </div>
</div>
<div class="sidebar" id="sidebar">
   <% if user_signed_in? %>
   <a href="/"><i class="fas fa-home">ホーム</i></a>
   <% end %>
   <% if user_signed_in? %>
   <a href="/"><i class="fa-sharp-duotone fa-solid fa-id-card">プロフィール</i></a>
   <% end %>
   <% if user_signed_in? %>
    <%= link_to "血糖値入力", new_glucose_path, class:"fa-solid fa-syringe" %> 
   <% end %>
   <% if user_signed_in? %>
    <%= link_to "血糖値データ", glucoses_path, class:"fa-solid fa-syringe" %> 
   <% end %>
   <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, class:"fa-solid fa-user", data: { turbo_method: :delete } %>   
   <% else %>
      <%= link_to "ログイン", new_user_session_path, class:"fa-solid fa-user" %> 
      <%= link_to "新規登録", new_user_registration_path, class: "fa-solid fa-user-plus"%>
   <% end %>
   <% if user_signed_in? %>
   <a href="#"><i class="fas fa-cog">設定</i></a>
   <% end %>
</div>